### PR TITLE
User Docs - Improvement: Adding learn zkSync by watching section, watch important videos by the zkSync team

### PR DESCRIPTION
**Pull request by stackaccount1**
Added a "Learn by Watching" section with important zkSync videos to the User Docs. It is important for visual learners and total new learners to be able to access these videos. 

## Description
Added learnbywatching.md file and updated the vuepress config file.

## Motivation and Context
These videos are very important to help people understand what zkSync is. Moving forward this will be a good section for people to know where to find zkSync tutorial videos, explanation videos, product videos, and etc. 

## How Has This Been Tested?
Tested locally on my computer

## Screenshots (if appropriate):
Attached.

zksyncvideosection

zksyncvideosection2

## Types of changes

- [ X] New feature (non-breaking change which adds functionality)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by StanislavBreadless — COMMENTED** [review]
Very nice! Could you please add more `margin` between the headers and the iframes? It seems to me that these are too close to each other

**Comment by stackaccount1** [comment]
Absolutely @StanislavBreadless, I will add more `margin` and resubmit PR. Thank you!

**Comment by stackaccount1** [comment]
@StanislavBreadless added, please see attached photos for a preview of that margin
learnbywatchingwmar
learnbywatchingwmar1
learnbywatchingwmar2
learnbywatchingwmar3

**Comment by StanislavBreadless** [comment]
Thank you @stackaccount1. I feel like the margins are a bit too big now :sweat_smile:. I'll just edit the margins on my local computer and re-open the PR from my account to let the CI pass

**Comment by stackaccount1** [comment]
> Thank you @stackaccount1. I feel like the margins are a bit too big now sweat_smile. I'll just edit the margins on my local computer and re-open the PR from my account to let the CI pass

Okay, sounds great!

**Comment by StanislavBreadless** [comment]
The new PR can be tracked here: https://github.com/matter-labs/zksync-docs/pull/161

**Pull request closed without merging**
