### PR TITLE
Java and Swift SDKs

### PR DESCRIPTION
**Pull request by AntonD3**
I divided it into different files(and increased the levels of headers) by analogy with other SDKs and added warnings about alpha versions.

In addition, I corrected the `Iterfaces` for `Interfaces` in Java SDK.

### CODE REVIEW

**Review by StanislavBreadless — CHANGES_REQUESTED** [review]
When I launched the app I couldn't find the tutorial, make sure to update `docs/.vuepress/config.js`

**Review by StanislavBreadless — COMMENTED** [review]
@popzxc I still can't see it. I'll help @AntonD3 if needed

**Comment by StanislavBreadless** [comment]
@AntonD3 Pls, the remove ForcedExit and FullExit pages, since these are rarely used and we don't usually mention them

**Comment by AntonD3** [comment]
> When I launched the app I couldn't find the tutorial, make sure to update `docs/.vuepress/config.js`

Ok, I added it to the `config.js`.

**Review by StanislavBreadless — APPROVED** [review]

**Pull request merged**
