### PR TITLE
Add sidebar navigation to zkEVM page

### PR DESCRIPTION
**Pull request by stackaccount1**
## Description
Add sidebar navigation to zkEVM page

## Motivation and Context
Help one navigate the information in this section.

## How Has This Been Tested?
locally on my computer

## Screenshots (if appropriate):
zkevmpr

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ na] New feature (non-breaking change which adds functionality)
- [ na] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ na] My change requires a change to the documentation.
- [ na] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ na] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by keriat** [comment]
@bxpana @StanislavBreadless take a look please

**Comment by bxpana** [comment]
> 
@keriat 
Everything looks good to me. I think it would be a good idea to have a sidebar

**Comment by StanislavBreadless** [comment]
LGTM

**Review by StanislavBreadless — APPROVED** [review]

**Comment by keriat** [comment]
Closed in favor of #232

**Pull request closed without merging**
